"""Configuration for the v1 memory reconciliation judge."""

from __future__ import annotations

from kivi_memory.common.config import DEFAULT_OLLAMA_BASE_URL, DEFAULT_OLLAMA_TIMEOUT_SECONDS

RECONCILIATION_MODEL = "qwen3.5:9b"
RECONCILIATION_TEMPERATURE = 0.0
RECONCILIATION_NUM_PREDICT = 32
RECONCILIATION_THINK = False
RECONCILIATION_MAX_CANDIDATES = 8
RECONCILIATION_OLLAMA_BASE_URL = DEFAULT_OLLAMA_BASE_URL
RECONCILIATION_OLLAMA_TIMEOUT_SECONDS = DEFAULT_OLLAMA_TIMEOUT_SECONDS
